### ISSUE TITLE
js console error

### ISSUE THREAD

**Issue by robbielove** [petehouston/laravel-tinymce-simple-imageupload#1]
While the images seem to upload fine, I was having issues with one view and discovered this message shows on pages with the 'tinymce init code at the top' included in them:

`Uncaught TypeError: Cannot read property 'uploadImages' of null`

**Comment by petehouston** [comment]
@robbielove does the text `Upload success` display?

**Comment by robbielove** [comment]
I just tested this and found no `Upload success` message, I simply select the image from the file dialog and it suddenly appears in the TinyMCE editor and then I save my object but don't see anything relating to `Upload success` while saving, it simply works.

**Comment by robbielove** [comment]
it seems i had tried previously to include image upload functionality and mistakenly thought it was part of the code you supplied, removing the offending code shows no error

`tinymce.activeEditor.uploadImages(function(success) {
   document.forms[0].submit();
});`

this is in the tinymce docs : https://www.tinymce.com/docs/get-started/upload-images/

no upload success message appears still. however i'm not convinced that one is meant to display...
