### ISSUE TITLE
Error when calling view

### ISSUE THREAD

**Issue by CharlyZA** [petehouston/laravel-tinymce-simple-imageupload#10]
Hi there

I'm having an issue with your plugin and I'd appreciate your help. Apologies if this is a newbie mistake but I have gone through your tutorial.

`No hint path defined for [mceImageUpload]. (View: C:\apps\store\resources\views\admin\blog\new.blade.php)`

I'm running Laravel 5.5

**Comment by petehouston** [comment]
Alright, so please re-install the package and try again. Please check installation part on README. Let me know if there is any problem. 

Thank you.
