### ISSUE TITLE
Error: undefined function resource_path()

### ISSUE THREAD

**Issue by 4LatamFede** [petehouston/laravel-tinymce-simple-imageupload#2]
Whoops, looks like something went wrong.
1/1 FatalErrorException in TinymceServiceProvider.php line 28: Call to undefined function Petehouston\Tinymce\resource_path()

    in TinymceServiceProvider.php line 28

**Comment by petehouston** [comment]
@4LatamFede how did you config your project and this package? What is your Laravel version? This package just works fine with Laravel 5.0+

**Comment by petehouston** [comment]
@4LatamFede Okay, so I've just looked into it. Could you try the latest version and give me the result **1.1.0**.

Fixed at laravel-tinymce-simple-imageupload

Thank you.
