### ISSUE TITLE
Class 'Petehouston\Tinymce\TinymceServiceProvider' not found

### ISSUE THREAD

**Issue by 4LatamFede** [petehouston/laravel-tinymce-simple-imageupload#3]
Hi, 

> latamar@4Latam-Federico:~$ composer require "petehouston/laravel-tinymce-simple-imageupload"
> Using version ^1.1 for petehouston/laravel-tinymce-simple-imageupload
> ./composer.json has been created
> Loading composer repositories with package information
> Updating dependencies (including require-dev)
>   - Installing paragonie/random_compat (v2.0.3)
>     Loading from cache
> 
>   - Installing illuminate/contracts (v5.3.16)
>     Loading from cache
> 
>   - Installing doctrine/inflector (v1.1.0)
>     Loading from cache
> 
>   - Installing illuminate/support (v5.3.16)
>     Loading from cache
> 
>   - Installing petehouston/laravel-tinymce-simple-imageupload (1.1.0)
>     Downloading: 100%         
> 
> paragonie/random_compat suggests installing ext-libsodium (Provides a modern crypto API that can be used to generate random bytes.)
> illuminate/support suggests installing illuminate/filesystem (Required to use the composer class (5.2.*).)
> illuminate/support suggests installing symfony/process (Required to use the composer class (3.1.*).)
> illuminate/support suggests installing symfony/var-dumper (Required to use the dd function (3.1.*).)
> Writing lock file
> Generating autoload files

And

>     /*
    |--------------------------------------------------------------------------
    | Autoloaded Service Providers
    |--------------------------------------------------------------------------
    |
    | The service providers listed here will be automatically loaded on the
    | request to your application. Feel free to add your own services to
    | this array to grant expanded functionality to your applications.
    |
    */

    'providers' => [

        /*
         * Laravel Framework Service Providers...
         */
        Illuminate\Foundation\Providers\ArtisanServiceProvider::class,
        Illuminate\Auth\AuthServiceProvider::class,
        Illuminate\Broadcasting\BroadcastServiceProvider::class,
        Illuminate\Bus\BusServiceProvider::class,
        Illuminate\Cache\CacheServiceProvider::class,
        Illuminate\Foundation\Providers\ConsoleSupportServiceProvider::class,
        Illuminate\Routing\ControllerServiceProvider::class,
        Illuminate\Cookie\CookieServiceProvider::class,
        Illuminate\Database\DatabaseServiceProvider::class,
        Illuminate\Encryption\EncryptionServiceProvider::class,
        Illuminate\Filesystem\FilesystemServiceProvider::class,
        Illuminate\Foundation\Providers\FoundationServiceProvider::class,
        Illuminate\Hashing\HashServiceProvider::class,
        Illuminate\Mail\MailServiceProvider::class,
        Illuminate\Pagination\PaginationServiceProvider::class,
        Illuminate\Pipeline\PipelineServiceProvider::class,
        Illuminate\Queue\QueueServiceProvider::class,
        Illuminate\Redis\RedisServiceProvider::class,
        Illuminate\Auth\Passwords\PasswordResetServiceProvider::class,
        Illuminate\Session\SessionServiceProvider::class,
        Illuminate\Translation\TranslationServiceProvider::class,
        Illuminate\Validation\ValidationServiceProvider::class,
        Illuminate\View\ViewServiceProvider::class,

        /*
         * Application Service Providers...
         */
        App\Providers\AppServiceProvider::class,
        App\Providers\EventServiceProvider::class,
        App\Providers\RouteServiceProvider::class,

        /*
        *   Laravel image
        */
        Petehouston\Tinymce\TinymceServiceProvider::class,
    ],

> Whoops, looks like something went wrong.
> 1/1 FatalErrorException in ProviderRepository.php line 146: Class 'Petehouston\Tinymce\TinymceServiceProvider' not found
> 
>     in ProviderRepository.php line 146
> 
> 

Thax, for your quick anwser..

**Comment by petehouston** [comment]
@4LatamFede I can't replicate your problem. You can push to a github repo, so I can investigate.
