### ISSUE TITLE
Unable to view the image

### ISSUE THREAD

**Issue by SandeepBanerjee** [petehouston/laravel-tinymce-simple-imageupload#5]
Hi i successfully add the images (Thank you very much for this), however i am unable to show the image it will look like this:
![sample](https://user-images.githubusercontent.com/8704829/27927067-2a789f06-62a8-11e7-8054-3b7ca8a95900.png)

**Comment by the94air** [comment]
I had the same problem. but I changed the file path in the `@include('mceImageUpload::upload_form')` view and it now works perfectly.

**Comment by a-ssassi-n** [comment]
@the94air I am facing the same issue, I am unable to find any specified file path in `upload_form` view. 
Could you please let me know what exactly did you changed??

**Comment by the94air** [comment]
@a-ssassi-n That is exactly what I did. It looks simple but completely powerful. It is so awesome.

**Comment by rambo666** [comment]
@a-ssassi-n and everybody else, I would not recomend you to edit any files residing in vendor as it will get updated with every composer updates. Therefore, You must create a new helper function somewhere in app directory and register in the AppServiceProvider.php. This way you can use your own version of helper service and you do not have to keep changing the vendor files. The above solution by @a-ssassi-n  is very effective but only for short period of time.

**Comment by the94air** [comment]
Thanks, @rambo666 I forgot to mention that in my comment. I have a helper file in my laravel app and I didn't edit the package helper file.
