### ISSUE TITLE
not compatible with laravel 5.7

### ISSUE THREAD

**Issue by howtomakeaturn** [petehouston/laravel-tinymce-simple-imageupload#8]
Hello, the new upgrade of laravel 5.7 make this package cannot work by default I think?

The 'or' operator has be removed.

So i think it has to be rewritten in other syntax?

https://laravel.com/docs/5.7/upgrade

Blade
The or Operator
Likelihood Of Impact: High

The Blade "or" operator has been removed in favor of PHP's built-in ?? "null coalesce" operator, which has the same purpose and functionality:

// Laravel 5.6...
{{ $foo or 'default' }}

// Laravel 5.7...
{{ $foo ?? 'default' }}

**Comment by howtomakeaturn** [comment]
and this is the file that has issue.

https://github.com/petehouston/laravel-tinymce-simple-imageupload/blob/master/src/views/upload_form.blade.php

**Comment by howtomakeaturn** [comment]
if you don't have time i can find a way to fix this and send PR.

**Comment by petehouston** [comment]
@howtomakeaturn thanks. It looks like the `or` operator has been removed from Laravel 5.7.

I will provide update to make it backward compatibility.
